apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: 270613068652.dkr.ecr.us-east-1.amazonaws.com/devows-project-eurekaserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
