apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 270613068652.dkr.ecr.us-east-1.amazonaws.com/devows-project-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_SPRING_BOOT_API_URL
              # Esto será inyectado por el pipeline con el DNS del ALB del API Gateway
              value: "http://API_GATEWAY_URL_PLACEHOLDER"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
