apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notificaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notificaciones
  template:
    metadata:
      labels:
        app: ms-notificaciones
    spec:
      containers:
        - name: ms-notificaciones
          image: 270613068652.dkr.ecr.us-east-1.amazonaws.com/devows-project-ms-notificaciones:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8095
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):5432/dnf_db"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-notificaciones
spec:
  selector:
    app: ms-notificaciones
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
